### ISSUE TITLE
Intro section

### ISSUE THREAD

**Issue by jamesgeorge007** [mad-hacks/hacktoberfest-website#1]
- [x] Hacktoberfest title
- [x] Captions
- [x] Background
- [x] Register now button linked up with the Jot form

**Comment by shanajames** [comment]
working..

**Comment by jerinjoseph1** [comment]
can i l do this

**Comment by shanajames** [comment]
Let's work together 👍

**Comment by jamesgeorge007** [comment]
Done :+1:
